# Numpy

## Task 1

You should import the necessary libraries. You will use `numpy` and `sys` libraries.


> Don't forget to import `numpy` in the short form.

In [7]:
import sys
import numpy as np

## Task 2

Create arrays with using Python default syntax and using `numpy`. Also, print the size of the arrays in bytes. You should use `sys` library for this task.

Requirements for arrays:
* length of the array should be `1000`;
* array should contain zeros;
* the second array should be generated by `numpy` library, and should have as little memory as possible.

In [3]:
arr = [0] * 1000
sys.getsizeof(arr)

8056

In [4]:
arr_np = np.zeros(1000, dtype=np.int8)
sys.getsizeof(arr_np)

1112

## Task 3

Write manually a small float array using `numpy` syntax number should be in the range from `0` to `10.0`. Also, you should get the first, the third, and the last elements of the array using multi-indexing.

Requirements:
* length of the array should be from `5` to `10`.

In [8]:
float_arr = np.array([1.2, 4.5, 7.8, 3.4, 9.1, 0.2, 5.6], dtype=np.float32)
float_arr = float_arr[[1,3,-1]]
print(float_arr)

[4.5 3.4 5.6]


## Task 4

You have the array `array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])` using multi-indexing you should summarize a subsequence of an array and get the `27` as the result.

In [12]:
array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])
result = array[[0, 1, 4, 7]]
result = np.sum(result)

np.float64(27.0)

## Task 5

You have a matrix `A`:

```python
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])
```

Follow the comments in the next cells and write the code.

In [15]:
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])

### Task 5.1 Find the mean for each column by `x` axis

In [17]:
A.mean(axis=0)

array([2. , 8.4])

### Task 5.2 Get the standard deviation by `y` axis

In [18]:
A.std(axis=1)

array([2.5, 3. , 4. , 3.5, 3. ])

### Task 5.3 Get the sum of all elements in `A` by `y` axis

In [19]:
A.sum(axis=1)

array([ 7, 10, 14, 13,  8])

### Task 5.4 Get the following result using multi-dim selection:

```python
[
    [1, 6],
    [2, 8],
 ]
```

In [21]:
A[[0,1]]

array([[1, 6],
       [2, 8]])

##  Task 5.5. Get the following result using multi-dim selection:
```python
[
    [1, 6],
    [3, 11],
    [1, 7]
 ]
```

In [22]:
A[[0,2,-1]]

array([[ 1,  6],
       [ 3, 11],
       [ 1,  7]])

## Task 6

Rewrite Python code to `numpy` code. Also, estimate the time of execution for both implementations.

> Please, note: `unknown_signature` this name just hide the real name of the function, to make the task more complicated.

### Task 6.1

In [31]:
# Python code
%timeit python_lst = [i for i in range(1_000_000)]

134 ms ± 7 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [32]:
%timeit np.arange(1_000_000)

5.52 ms ± 91.7 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


### Task 6.2

In [47]:
# Python code
def unknown_signature(vector1, vector2):
    result = 0
    for i in range(len(vector1)):
        result += vector1[i] * vector2[i]
    return result

vector1 = [1, 2, 3]
vector2 = [4, 5, 6]
result = 0

%timeit result = unknown_signature(vector1, vector2)
unknown_signature(vector1, vector2)

985 ns ± 66.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


32

In [48]:
%timeit np.sum(np.multiply(vector1, vector2))
np.sum(np.multiply(vector1, vector2))

9.46 μs ± 507 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


np.int64(32)

### Task 6.3

In [5]:
# Python code
def unknown_signature(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[i])):
            row.append(matrix1[i][j] * matrix2[i][j])
        result.append(row)
    return result

matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]
%timeit unknown_signature(matrix1, matrix2)
unknown_signature(matrix1, matrix2)

The slowest run took 5.77 times longer than the fastest. This could mean that an intermediate result is being cached.
3.01 μs ± 2.19 μs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


[[5, 12], [21, 32]]

In [8]:
%timeit np.multiply(matrix1, matrix2)
np.multiply(matrix1, matrix2)

4.11 μs ± 1.02 μs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


array([[ 5, 12],
       [21, 32]])

### Task 6.4

In [9]:
# Python code
def unknown_signature(lst):
    total = 0
    for num in lst:
        total += num
    result = total / len(lst)
    return result

lst = [1, 2, 3, 4, 5]
%timeit unknown_signature(lst)
unknown_signature(lst)

495 ns ± 58.9 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


3.0

In [11]:
%timeit np.mean(lst)
np.mean(lst)

13.1 μs ± 1.66 μs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


np.float64(3.0)

## Task 7

Rewrite Python code to `numpy` code (Masks).

### Task 7.1

In [13]:
# Python code
def unknown_signature(lst, mask, new_value):
    for i in range(len(lst)):
        if mask[i]:
            lst[i] = new_value

lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0
unknown_signature(lst, mask, new_value)
lst


[0, 2, 0, 4, 0]

In [14]:
lst_array = np.array([1, 2, 3, 4, 5])
lst_array[mask] = 0
lst_array

array([0, 2, 0, 4, 0])

### Task 7.2

In [15]:
# Python code
def unknown_signature(lst1, lst2):
    bitwise_complement = [~x for x in lst1]
    bitwise_and = [x & y for x, y in zip(lst1, lst2)]
    bitwise_or = [x | y for x, y in zip(lst1, lst2)]
    return bitwise_complement, bitwise_and, bitwise_or

list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]
result_bitwise_complement, result_bitwise_and, result_bitwise_or = unknown_signature(list1, list2)
result_bitwise_complement, result_bitwise_and, result_bitwise_or

([-6, -3, -8, -5, -10], [1, 2, 1, 0, 8], [7, 6, 7, 12, 11])

In [22]:
def unknown_signature(lst1, lst2):
    arr1 = np.array(lst1)
    arr2 = np.array(lst2)
    bitwise_complement = np.bitwise_not(arr1)
    bitwise_and = np.bitwise_and(arr1, arr2)
    bitwise_or = np.bitwise_or(arr1, arr2)
    
    return bitwise_complement, bitwise_and, bitwise_or

list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]
result_bitwise_complement, result_bitwise_and, result_bitwise_or = unknown_signature(list1, list2)
(result_bitwise_complement.tolist(),
result_bitwise_and.tolist(),
result_bitwise_or.tolist())

([-6, -3, -8, -5, -10], [1, 2, 1, 0, 8], [7, 6, 7, 12, 11])

### Task 7.3 Optional

In [23]:
# Python code
def unknown_signature(lst):
    result = []
    for num in lst:
        if num % 2 == 0 and (num % 3 == 0 or num > 10):
            modified_num = (num ^ 7) + 2
            result.append(modified_num)
    return result

my_list = [6, 9, 12, 14, 17, 20]
result_python_style = unknown_signature(my_list)
result_python_style

[3, 13, 11, 21]

In [25]:
def unknown_signature(lst):
    arr = np.array(lst)
    condition = (arr % 2 == 0) & ((arr % 3 == 0) | (arr > 10)) 
    modified_nums = (arr[condition] ^ 7) + 2
    
    return modified_nums.tolist()

my_list = [6, 9, 12, 14, 17, 20]
result_numpy_style = unknown_signature(my_list)
result_numpy_style

[3, 13, 11, 21]